;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-kill-whole-line
        crux-move-beginning-of-line
        crux-smart-open-line
        crux-smart-open-line-above
        easy-kill
        indent-for-tab-command
        kill-region
        sp-backward-sexp
        sp-backward-up-sexp
        sp-down-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        crux-find-user-init-file
        end-of-buffer
        ))
