;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sexp
        consult-yank-replace
        crux-kill-line-backwards
        crux-kill-whole-line
        crux-move-beginning-of-line
        crux-smart-open-line
        crux-smart-open-line-above
        crux-top-join-line
        dabbrev-expand
        easy-kill
        indent-for-tab-command
        kill-region
        sp-backward-down-sexp
        sp-backward-kill-sexp
        sp-backward-sexp
        sp-backward-up-sexp
        sp-beginning-of-sexp
        sp-down-sexp
        sp-end-of-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-sexp
        sp-mark-sexp
        sp-rewrap-sexp
        sp-splice-sexp
        sp-up-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        beginning-of-buffer
        crux-find-user-init-file
        end-of-buffer
        find-file
        magit-status
        mouse-set-region
        rspec-rerun
        rspec-verify
        toggle-debug-on-quit
        ))
